version: '3.8'

services:
  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    restart: unless-stopped
